### ISSUE TITLE
CMC Comparison hue angle/degree mismatch

### ISSUE THREAD

**Issue by torokze** [THEjoezack/ColorMine#36]
Hello,

During the CMC calculation:

// this yields result between +/- π radians
var h = Math.Atan2(aLab.B, aLab.A);

// Later you using h as degrees !!!!
var t = 164 <= h || h >= 345
// Math.cos expects radians
           ? .56 + Math.Abs(.2 \* Math.Cos(h + 168.0))
           : .36 + Math.Abs(.4 \* Math.Cos(h + 35.0));

I'm confused.

**Comment by tompazourek** [comment]
**You are right** that you need to convert from radians to degrees. But I don't understand how it's possible, since the code is tested:

https://github.com/THEjoezack/ColorMine/blob/master/ColorMine.Test/ColorSpaces/Comparisons/CmcComparisonTest.cs

--------

About a year ago I wrote an implementation of CMC difference calculations as part of my [Colourful](https://github.com/tompazourek/Colourful) library.

Maybe my implementation will be helpful:
https://github.com/tompazourek/Colourful/blob/master/Colourful/Difference/CMCColorDifference.cs

Not many unit tests though, but still at least something:
https://github.com/tompazourek/Colourful/blob/master/Colourful.Tests/ColorDifferenceFormulasTest.cs#L173

Use these freely.

**Comment by THEjoezack** [comment]
Fixed in https://github.com/THEjoezack/ColorMine/pull/46
