### ISSUE TITLE
bug in CmcComparison.cs

### ISSUE THREAD

**Issue by hunter1085** [THEjoezack/ColorMine#40]
in the interface 
          public double Compare(IColorSpace colorA, IColorSpace colorB)

when calculate :
var deltaH = Math.Sqrt(
                (aLab.A - bLab.A) \* (aLab.A - bLab.A) +
                (aLab.B - bLab.B) \* (aLab.B - bLab.B) - 
                deltaC \* deltaC);

the value pass to
Sqrt()
may less than 0. In such case, the comparison fails.
Consider the following 2 sample color for a test
ColorA with [L,A,B]=(0.0, 0.0, 0.0)
ColorB with [L,A,B]=(41.41, 2.64, 4.15)

**Comment by tompazourek** [comment]
The square root of `deltaH` doesn't need to be computed at all, because when `deltaH` is used afterwards, it's squared again. So it's possible to avoid using square root in that case. I had the same issue in a .NET library called [Colourful](https://github.com/tompazourek/Colourful) that I'm maintaining.

See this commit for a solution:

https://github.com/tompazourek/Colourful/commit/90a3ff848784ce430a465723890a867852a251ae

**Comment by THEjoezack** [comment]
Awesome, great point! Thanks!

**Comment by THEjoezack** [comment]
Fixed in https://github.com/THEjoezack/ColorMine/pull/46
